#include <furi.h>
#include <furi/core/message_queue.h>
#include <gui/canvas.h>
#include <gui/view_port.h>
#include <gui/gui.h>
#include <input/input.h>

/* generated by fbt from .png files in images folder */

void new_frame_callback(Canvas* canvas, void* context);

void new_frame_callback(Canvas* canvas, void* context) {
    UNUSED(context);
    
    int i;
    for (i = 0; i < 80; i = i + 5) {
        canvas_draw_str(canvas, 50, i, "Olle-san");
    }
};

void input_handler(InputEvent* input_event, void* context);

void input_handler(InputEvent* input_event, void* context) {
    furi_assert(context);
    FuriMessageQueue* event_queue = context;

    furi_message_queue_put(event_queue, input_event, FuriWaitForever);
};

int32_t test_run(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");

    FuriMessageQueue* queue = furi_message_queue_alloc(8, sizeof(InputEvent));

    ViewPort* view_port = view_port_alloc();
    view_port_draw_callback_set(view_port, new_frame_callback, NULL);
    view_port_input_callback_set(view_port, input_handler, queue);
    
    Gui* gui = furi_record_open(RECORD_GUI);
    gui_add_view_port(gui, view_port, GuiLayerFullscreen);

    InputEvent event;
    bool running = true;
    while(running) {
        if(furi_message_queue_get(queue, &event, 100) == FuriStatusOk) {
            if(event.type == InputTypeShort && event.key == InputKeyBack) {
                running = false;
            }
        }
    }

    // Cleanup in reverse order
    gui_remove_view_port(gui, view_port);
    furi_record_close(RECORD_GUI);
    view_port_free(view_port);
    furi_message_queue_free(queue);

    return 0;
}
